/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sxc.saman.SIS.GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dipesh
 */
public class DashboardStaff extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
  
    public DashboardStaff() {
        initComponents();
        Toolkit thekit = getToolkit();
        Dimension d = thekit.getScreenSize();
     System.out.println("Staffs");
        setSize(d);
        setResizable(false);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        changeMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        logoutMenuItem = new javax.swing.JMenuItem();
        addUserMenuItem = new javax.swing.JMenu();
        searchUserMenuItem = new javax.swing.JMenuItem();
        searchStudentsMenuItem = new javax.swing.JMenuItem();
        SearchTeacherMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        changeMenuItem.setText("Change Password");
        changeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(changeMenuItem);
        jMenu1.add(jSeparator1);

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoutMenuItem);

        jMenuBar1.add(jMenu1);

        addUserMenuItem.setText("Edit");

        searchUserMenuItem.setText("Search User");
        searchUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserMenuItemActionPerformed(evt);
            }
        });
        addUserMenuItem.add(searchUserMenuItem);

        searchStudentsMenuItem.setText("Search Student");
        addUserMenuItem.add(searchStudentsMenuItem);

        SearchTeacherMenuItem.setText("Search Teacher");
        addUserMenuItem.add(SearchTeacherMenuItem);
        addUserMenuItem.add(jSeparator2);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        addUserMenuItem.add(exitMenuItem);

        jMenuBar1.add(addUserMenuItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserMenuItemActionPerformed
        setContentPane(new UserSearch());
        revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_searchUserMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void changeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeMenuItemActionPerformed
        new ChangePassword();

    }//GEN-LAST:event_changeMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure", "Warning", dialogBtn);
        if (dialogResult == JOptionPane.YES_OPTION) {
            setVisible(false);
            new LoginDialog();
        }
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SearchTeacherMenuItem;
    private javax.swing.JMenu addUserMenuItem;
    private javax.swing.JMenuItem changeMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuItem searchStudentsMenuItem;
    private javax.swing.JMenuItem searchUserMenuItem;
    // End of variables declaration//GEN-END:variables
}
